userName: BROWSERSTACK_USERNAME
accessKey: BROWSERSTACK_ACCESS_KEY
app: ./WikipediaSample.apk
platforms:
  - platformName: android
    platformVersion: 12.0
    deviceName: Samsung Galaxy S22 Ultra
  - platformName: android
    platformVersion: 13.0
    deviceName: Google Pixel 7 Pro
  - platformName: android
    platformVersion: 11.0
    deviceName: OnePlus 9
buildIdentifier: ${BUILD_NUMBER}
projectName: Pytest Tests
buildName: automation-test-
debug: true
testObservability: true